# Generated by Django 4.2.4 on 2023-12-16 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('customer_card_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'cards',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Checks',
            fields=[
                ('check_id', models.AutoField(primary_key=True, serialize=False)),
                ('sku_amount', models.DecimalField(decimal_places=3, max_digits=12)),
                ('sku_summ', models.DecimalField(decimal_places=3, max_digits=12)),
                ('sku_summ_paid', models.DecimalField(decimal_places=3, max_digits=12)),
                ('sku_discount', models.DecimalField(decimal_places=3, max_digits=12)),
            ],
            options={
                'db_table': 'checks',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GroupsSku',
            fields=[
                ('group_id', models.AutoField(primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'groups_sku',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PersonalData',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_surname', models.CharField(max_length=255)),
                ('customer_primary_email', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_primary_phone', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'db_table': 'personal_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sku',
            fields=[
                ('sku_id', models.AutoField(primary_key=True, serialize=False)),
                ('sku_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'sku',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Stores',
            fields=[
                ('transaction_store_id', models.AutoField(primary_key=True, serialize=False)),
                ('sku_purchase_price', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('sku_retail_price', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
            ],
            options={
                'db_table': 'stores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_summ', models.DecimalField(decimal_places=3, max_digits=12)),
                ('transaction_datetime', models.DateTimeField()),
            ],
            options={
                'db_table': 'transactions',
                'managed': False,
            },
        ),
    ]
