# Use postgres/example user/password credentials
version: '3.1'

services:
  db: 
    build:
      context: ./db
      dockerfile: ./Dockerfile
    image: retail_postgres
    container_name: retail_postgres    
    volumes:
      - pg_ret:/var/lib/postgresql    
    env_file:
      - ./db/db.env      
    ports:
      - 55432:5432
    networks:
      - retail_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d pgretail" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
  frontend:
    build:
      context: frontend/
      dockerfile: ./Dockerfile
    container_name: "retail_frontend"
    image: retail_frontend
    restart: unless-stopped
    stop_grace_period: 10s
    networks:
      - retail_network
  nginx:
    image: "nginx"
    volumes:
      - ./configs/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    container_name: nginx
    networks:
      - retail_network
    restart: unless-stopped
    depends_on: 
      db:
        condition: service_started
      frontend:
        condition: service_healthy

volumes:
  pg_ret:

networks:
  retail_network:
